# write a python program that manipulates and prints strings using various string methods.
str_temp = "Tops Technologies"
print (len(str_temp))
print (str_temp.lower())
print (str_temp.upper())
print (str_temp.capitalize())
print (str_temp.title())
print (str_temp.strip())
print (str_temp.replace("T","O",1))
print (str_temp.find("T"))
print (str_temp.startswith("T"))
print (str_temp.startswith("s"))
print (str_temp.endswith("s"))
print (str_temp.split("T",3))
print ("*".join(str_temp))
print (str_temp.isalpha())
print (str_temp.isdigit())
print (str_temp.isalnum())
print (str_temp.zfill(20))